name: toolspaedeia

volumes:
  local_postgres_data: {}

services:

  web:
    build:
      context: .
    container_name: toolspaedeia_web
    platform: linux/x86_64
    command: >
      sh -c "python manage.py migrate &&
            uvicorn toolspaedeia.asgi:application --host 0.0.0.0 --port 8888 --reload"
    ports:
      - "8888:8888"
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:latest
    container_name: toolspaedeia_postgres
    environment:
      POSTGRES_HOST: "postgres"
      POSTGRES_PORT: "5432"
      POSTGRES_DB: "toolspaedeia"
      POSTGRES_USER: "root"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    ports:
      - "8889:5432"
    volumes:
      - local_postgres_data:/var/lib/postgresql:Z
    healthcheck:
      test: "CMD-SHELL pg_isready -U postgres"
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  redis:
    image: redis:latest
    container_name: toolspaedeia_redis
