name: toolspaedeia

volumes:
  local_postgres_data: {}

services:

  web:
    build:
      context: .
    container_name: toolspaedeia_web
    platform: linux/x86_64
    command: uvicorn toolspaedeia.asgi:application --host 0.0.0.0 --port 8888 --reload
    ports:
      - "8888:8888"
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:latest
    container_name: toolspaedeia_postgres
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - local_postgres_data:/var/lib/postgresql:Z

  redis:
    image: redis:latest
    container_name: toolspaedeia_redis
