[project]
name = "toolspaedeia"
version = "0.1.0"
description = "A collection of tools for learning"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=5.2.9",
    "matplotlib>=3.10.7",
    "uvicorn>=0.38.0",
]
